<template>
  <v-row justify="center" align="center">
    <v-col cols="12" sm="8" md="6">
      <div class="text-center">
        <h1 style="font-size: 50px">
          About <span class="special-color">Tree</span>Gen
        </h1>
      </div>
      <v-card class="rounded-card">
        <v-flex class="main-box">
          <p>
            TreeGen is a software developed by students on the BBSRC
            Interdisciplinary Bioscience DTP at the University of Oxford.
          </p>
          <h3>What is TreeGen?</h3>
          <p>
            TreeGen generates and animates the biological patterns that can be
            obtained using Lindenmayer systems with graphical modeling, as
            described in the textbook “The Algorithmic Beauty of Plants”. This
            web application allows you to visualise the fractal-like biological
            patterns that can be generated using simple OL-systems.
          </p>
          <h3>Usage</h3>
          <p>
            To use TreeGen, simply go to the page 'Draw Trees', select the
            parameters you want (or keep the default parameters) and click
            anywhere on the canvas to draw a tree.
          </p>
          <h3>L-systems</h3>
          <p>
            A Lindenmayer system, or L-system for short, is a recursive
            framework that consists of an alphabet of symbols that can be used
            to make strings, a set of production rules that define the way each
            symbol can be iteratively replaced by a larger string of symbols,
            and an axiom which is an initial string from which to begin
            construction.
            <br />
            The L-system can then be visually represented as a geometric
            structure, which is generated by a 'turtle' mechanism that
            translates the strings generated by the L-system.
          </p>

          <p />
          <p>
            L-systems can be used to model the growth processes of trees using
            computer-generated plant-like structures that imitate biological
            patterns.
          </p>
          <p>
            The L-systems that TreeGen uses to generate trees are context-free
            (OL-systems). In OL-systems, the production rules apply
            independently from the context in which the previous generations
            were generated. TreeGen does not support tree generation using
            context-sensitive L-systems, where the production rules depend on
            the predecessor's context.
          </p>
          <p>
            You can read more about L-systems by following the links on our
            'Links' page!
          </p>
          <h3>Parameters</h3>
          <p>
            OL-systems can be either deterministic (DOL-systems) or stochastic.
            TreeGen allows you to explore the structures that can be generated
            by both of these types of models.
          </p>
          <ul>
            <li>
              In <b>deterministic</b> L-systems, the same rules are applied at
              each step of the generation of the tree's structure. All trees
              generated by a deterministic L-system with the same parameters
              will be identical.
              <br />
              To generate a deterministic tree, select System Rules:
              'Deterministic' in the parameters, then choose a production rule
              for X and for F in the dropdown menus below. You can also specify
              your own custom rule for X and/or F by selecting 'Custom' and
              typing your rule in the textbox below (make sure your rule is
              using the same syntax as the ones proposed).
            </li>
            <br />
            <li>
              In <b>stochastic</b> L-systems, the production rules applied at
              each step of tree generation are selected stochastically according
              to a pre-defined probability distribution. Each rendition of the
              tree is then different from the others. To generate a stochastic
              tree, select System Rules: 'Stochastic' in the parameters. <br />
              Note: TreeGen only allows for a uniform probability distribution
              across the rules listed in the menu.
            </li>
          </ul>
          <br />
          <p>
            You can specify the value of the branching angle (i.e. the angle at
            which the new branches will form with respect to the previous
            branch) and whether the angle should be deterministic or stochastic
            (with either 1% or 0.1% variability from specified value).
          </p>
          <p>
            You can also specify the length scale of the tree branches, and
            whether the branch lengths should be deterministic or stochastic
            (with either 10% or 50% variability from specified value).
          </p>
          <p>
            Lastly, use the 'RESET' button to set the parameters back to default
            and the 'CLEAR' button to clear the canvas from all drawn tree
            structures.
          </p>
        </v-flex>
      </v-card>
    </v-col>
  </v-row>
</template>

<style scoped>
h1 .special-color {
  color: greenyellow;
}

p {
  color: rgb(180, 180, 180);
}
li {
  color: rgb(180, 180, 180);
}
h3 {
  color: greenyellow;
}

.rounded-card {
  border-radius: 25px;
}

.main-box {
  padding: 20px;
}
</style>
